import { PurchaseItem } from "./types";
import { genId, hoursAgo } from "./utils";

export const INITIAL_ITEMS: PurchaseItem[] = [
  {
    id: genId("item"),
    name: "Sony WH-1000XM6 Headphones",
    url: "https://electronics.example.com/sony-wh1000xm6",
    price: 399,
    category: "Tech & Gadgets",
    note: "My current pair still works fine, but these have better noise cancelling and I saw a really good ad for them this morning.",
    createdAt: hoursAgo(20 * 24 + 3),
    coolingHours: 30 * 24,
    status: "cooling",
    votes: [
      { choice: "dont-buy", tags: ["Hype Train", "You already own this"] },
      { choice: "dont-buy", tags: ["You already own this"] },
      { choice: "dont-buy", tags: ["Overpriced"] },
      { choice: "buy", tags: [] },
    ],
    alternatives: [
      {
        id: genId("alt"),
        authorName: "Priya M.",
        type: "Cheaper Link",
        description: "Sony WH-1000XM5 open box, same ANC chip, 30% cheaper.",
        url: "https://refurb.example.com/sony-wh1000xm5",
        createdAt: hoursAgo(18 * 24),
      },
      {
        id: genId("alt"),
        authorName: "Dev K.",
        type: "Will Lend Mine",
        description: "I have the XM5s and barely use them anymore, happy to lend for a week so you can compare.",
        createdAt: hoursAgo(15 * 24),
      },
    ],
  },
  {
    id: genId("item"),
    name: "Oversized Wool Coat — Aritzia",
    url: "https://fashion.example.com/aritzia-oversized-wool-coat",
    price: 228,
    category: "Fashion & Apparel",
    note: "Saw it in a TikTok haul and it looked like it would go with basically everything I already own.",
    createdAt: hoursAgo(2 * 24 + 6),
    coolingHours: 14 * 24,
    status: "cooling",
    votes: [
      { choice: "dont-buy", tags: ["Hype Train", "Fast Fashion"] },
      { choice: "buy", tags: [] },
      { choice: "buy", tags: [] },
    ],
    alternatives: [
      {
        id: genId("alt"),
        authorName: "Sam O.",
        type: "DIY Option",
        description: "A local tailor can add oversized wool lapels to a plain coat for a fraction of the price — sent you a pattern link.",
        createdAt: hoursAgo(1 * 24),
      },
    ],
  },
  {
    id: genId("item"),
    name: "Standing Desk Converter",
    url: "https://home.example.com/standing-desk-converter",
    price: 189,
    category: "Home & Decor",
    note: "My back has been hurting after long work sessions, this feels like a genuinely practical fix and not just an impulse.",
    createdAt: hoursAgo(7 * 24 - 5),
    coolingHours: 7 * 24,
    status: "cooling",
    votes: [
      { choice: "buy", tags: [] },
      { choice: "buy", tags: [] },
      { choice: "buy", tags: [] },
      { choice: "dont-buy", tags: ["Better alt exists"] },
    ],
    alternatives: [
      {
        id: genId("alt"),
        authorName: "Marcus T.",
        type: "DIY Option",
        description: "Stack of sturdy boxes plus a $12 keyboard tray gets you 80% of the ergonomic benefit for a weekend project.",
        createdAt: hoursAgo(4 * 24),
      },
      {
        id: genId("alt"),
        authorName: "Elena R.",
        type: "Cheaper Link",
        description: "Found the same model, unbranded, for $95 on a restaurant-supply site — desk risers are the same part.",
        url: "https://supply.example.com/adjustable-riser",
        createdAt: hoursAgo(3 * 24),
      },
    ],
  },
  {
    id: genId("item"),
    name: "Nintendo Switch 2",
    url: "https://games.example.com/nintendo-switch-2",
    price: 449.99,
    category: "Hobby & Gaming",
    note: "Every friend in my group chat has one now and I keep missing out on co-op sessions. Probably peer pressure.",
    createdAt: hoursAgo(30 * 24 + 2),
    coolingHours: 30 * 24,
    status: "cooling",
    votes: [
      { choice: "dont-buy", tags: ["Hype Train"] },
      { choice: "dont-buy", tags: ["Hype Train", "Overpriced"] },
      { choice: "buy", tags: [] },
      { choice: "buy", tags: [] },
      { choice: "dont-buy", tags: ["Will collect dust"] },
    ],
    alternatives: [
      {
        id: genId("alt"),
        authorName: "Jordan F.",
        type: "Will Lend Mine",
        description: "I upgraded and my old console is just sitting in a drawer — you can borrow it for a real trial run first.",
        createdAt: hoursAgo(10 * 24),
      },
    ],
  },
  {
    id: genId("item"),
    name: "Le Creuset Dutch Oven, 5.5qt",
    url: "https://kitchen.example.com/le-creuset-dutch-oven",
    price: 380,
    category: "Home & Decor",
    note: "It's beautiful and every cooking video uses one, but I already have a perfectly good enameled pot.",
    createdAt: hoursAgo(45 * 24),
    coolingHours: 21 * 24,
    status: "saved",
    votes: [
      { choice: "dont-buy", tags: ["You already own this", "Overpriced"] },
      { choice: "dont-buy", tags: ["You already own this"] },
    ],
    alternatives: [
      {
        id: genId("alt"),
        authorName: "Nina P.",
        type: "Cheaper Link",
        description: "Lodge enameled dutch oven performs almost identically in blind cooking tests, quarter of the price.",
        url: "https://kitchen.example.com/lodge-enameled",
        createdAt: hoursAgo(40 * 24),
      },
    ],
    resolution: {
      reason: "It's genuinely useful",
      resolvedAt: hoursAgo(24 * 24),
    },
  },
  {
    id: genId("item"),
    name: "Limited Edition Collab Sneakers",
    url: "https://footwear.example.com/limited-collab-sneakers",
    price: 260,
    category: "Fashion & Apparel",
    note: "Drop sells out fast, felt like I had to decide immediately or lose the chance forever.",
    createdAt: hoursAgo(60 * 24),
    coolingHours: 5 * 24,
    status: "bought",
    votes: [
      { choice: "buy", tags: [] },
      { choice: "dont-buy", tags: ["Hype Train"] },
    ],
    alternatives: [],
    resolution: {
      reason: "Ran out of patience",
      resolvedAt: hoursAgo(55 * 24),
    },
  },
];
